SinemaSONDeneme/CinemaAutomation-master/CinemaAutomation/Project.MVCUI/Areas/Admin/Controllers/RealMovieController.cs
using Project.BLL.RepositoryPattern.ConcreteRepository;
using Project.COMMON.Tools;
using Project.MODEL.Entities;
using Project.MVCUI.AuthenticationClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Areas.Admin.Controllers
{
    
   [MultiAuthentication]
    public class RealMovieController : Controller
    {
        MovieRepository movp;
        MovieGenreRepository genrp;
        public RealMovieController()
        {
            movp = new MovieRepository();
            genrp = new MovieGenreRepository();
        }
        // GET: Admin/RealMovie
      
        public ActionResult MovieList()
        {
            return View(movp.SelectActives());
        }
        public ActionResult AddMovie()
        {
            return View(Tuple.Create(genrp.SelectActives(), new Movie()));
        }
        [HttpPost]
        public ActionResult AddMovie([Bind(Prefix = "Item2")] Movie item, HttpPostedFileBase resim)
        {
            item.ImagePath = ImageUploader.UploadImage("~/Pictures/", resim);
            movp.Add(item);
            return RedirectToAction("MovieList");
        }
        public ActionResult MovieDetail(int id)
        {
            return View(movp.Default(x => x.ID == id));
        }
        public ActionResult DeleteMovie(int id)
        {
            movp.Delete(movp.GetByID(id));
            return RedirectToAction("MovieList");
        }
        public ActionResult UpdateMovie(int id)
        {
            return View(Tuple.Create(genrp.SelectActives(), movp.GetByID(id)));
        }
        [HttpPost]
        public ActionResult UpdateMovie([Bind(Prefix = "Item2")] Movie item, HttpPostedFileBase resim, string resimSil)
        {
            if (resimSil == "true")
            {
                item.ImagePath = "Dosya boş";
            }
            else
            {

                if (resim == null)
                {
                    Movie tempMovie = movp.GetByID(item.ID);
                    item.ImagePath = tempMovie.ImagePath;

                }
                else
                {
                    item.ImagePath = ImageUploader.UploadImage("~/Pictures/", resim);
                }
            }

            movp.Update(item);
            return RedirectToAction("MovieList");
        }
    
    }
}

SinemaSONDeneme/CinemaAutomation-master/CinemaAutomation/Project.MVCUI/Areas/Admin/Views/RealMovie/AddMovie.cshtml
@model Tuple<List<MovieGenre>, Movie>
@{
    ViewBag.Title = "AddMovie";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="panel-body">
    <div class="form">
        @using (Html.BeginForm("AddMovie", "RealMovie", FormMethod.Post, new { @class = "cmxform form-horizontal tasi-form", enctype = "multipart/form-data" }))
        {
           
            <div class="form-group ">
                <label for="firstname" class="control-label col-lg-2">Film Adı</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.MovieName, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group ">
                <label for="lastname" class="control-label col-lg-2">Film Süresi</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.ScreenTime, new { @class = "form-control", type = "number" })

                </div>
            </div>
            <div class="form-group ">
                <label for="username" class="control-label col-lg-2">Türü</label>
                <div class="col-lg-6">
                    @Html.DropDownListFor(x => x.Item2.MovieGenreID, new SelectList(Model.Item1, "ID", "GenreName"), "Lutfen Seçiniz", new { @class = "form-control" })

                </div>
            </div>
            <div class="form-group ">
                <label for="description" class="control-label col-lg-2">Özet</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.MovieSummary, new { style = "height:100px;width:600px" })
                </div>
            </div>
            <div class="form-group ">
                <label for="password" class="control-label col-lg-2">Formatlar</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.Format, new { @class = "form-control", type = "string" })

                </div>
            </div>
            <div class="form-group ">
                <label for="lastname" class="control-label col-lg-2">Vizyon Tarihi</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.ShowDate, new { @class = "form-control", type = "datetime" })
                </div>
            </div>
            <div class="form-group ">
                <label for="firstname" class="control-label col-lg-2">Yönetmen</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.Director, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group ">
                <label for="firstname" class="control-label col-lg-2">Oyuncular</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.Actors, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2">Fotoğraf Yükle</label>
                <div class="col-md-9">
                    <div class="fileupload fileupload-new" data-provides="fileupload">
                        <div class="fileupload-new thumbnail" style="width: 570px; height: 516px;">
                            <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" />
                        </div>
                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                        <div>
                            <span class="btn btn-white btn-file">
                                <span class="fileupload-new"><i class="icon-paper-clip"></i> Fotoğraf Seç</span>
                                <span class="fileupload-exists"><i class="icon-undo"></i> Değiştir</span>
                                <input name="resim" type="file" class="default" />
                            </span>
                            <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="icon-trash"></i> Fotoğrafı Kaldır</a>
                        </div>
                    </div>

                </div>
            </div>



            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-6">
                    <button class="btn btn-danger" type="submit">Gönder</button>
                    @Html.ActionLink("İptal Et", "MovieList", null, new { @class = "btn btn-default" })

                </div>
            </div>


        }
    </div>
</div>

SinemaSONDeneme/CinemaAutomation-master/CinemaAutomation/Project.MVCUI/Areas/Admin/Views/RealMovie/MovieDetail.cshtml
@model Movie
@{
    ViewBag.Title = "MovieDetail";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="col-md-9">
    <section class="panel">
        <div class="panel-body">
            <div class="col-md-6">
                <div class="pro-img-details">
                    <img src="@Model.ImagePath" alt="" />
                </div>
                <div class="pro-img-list">
                    <a href="#">
                        <img src="" alt="">
                    </a>
                    <a href="#">
                        <img src="" alt="">
                    </a>
                    <a href="#">
                        <img src="" alt="">
                    </a>
                    <a href="#">
                        <img src="" alt="">
                    </a>
                    

                </div>
            </div>
            <div class="col-md-6">
                <h4 class="pro-d-title">
                    <a href="#" class="">
                        <h3>@Model.MovieName</h3>
                    </a>
                </h4> <br />
                <p>
                   
                </p>
                <div class="product_meta">
                    <span class="posted_in"> <strong>Tür:</strong> <a rel="tag" href="#">@Model.MovieGenre.GenreName</a></span>
                    <span class="tagged_as"><strong>Vizyon Tarihi :</strong> <a rel="tag" href="#">@Model.ShowDate</a>, <a rel="tag" href="#"></a>.</span>

                </div>
                <div class="m-bot15"> <strong>Süre : </strong>  <span class="pro-price">@Model.ScreenTime dakika</span></div>
                <div class="m-bot15"> <strong>Formatlar : </strong>  <span class="pro-price">@Model.Format </span></div>
                <div class="m-bot15"> <strong>Oyuncular : </strong>  <span class="pro-price">@Model.Actors </span></div>
                <div class="m-bot15"> <strong>Yönetmen : </strong>  <span class="pro-price">@Model.Director </span></div>
                <br /> <hr />


                <p>
                    @Html.ActionLink("Güncelle", "UpdateMovie", new { id = Model.ID }, new { @class = "btn btn-round btn-danger" })
                    @Html.ActionLink("Iptal Et", "MovieList", null, new { @class = "btn btn-round btn-default" })


                </p>
            </div>
        </div>
    </section>
    <section class="panel">
        <header class="panel-heading tab-bg-dark-navy-blue">
            <ul class="nav nav-tabs ">
                <li class="active">
                    <a data-toggle="tab" href="#description">
                        Özet
                    </a>
                </li>
                <li>
                    <a data-toggle="tab" href="#reviews">
                        Yorumlar
                    </a>
                </li>
            </ul>
        </header>
        <div class="panel-body">
          
            <div class="tab-content tasi-tab">
                <div id="description" class="tab-pane active">
                    
                    <p><h4 style="color:black">@Model.MovieSummary</h4> </p>
                   
                </div>
                <div id="reviews" class="tab-pane">
                    <article class="media">
                        <a class="pull-left thumb p-thumb">
                            <img src="img/avatar-mini.jpg">
                        </a>
                        <div class="media-body">
                            <a href="#" class="cmt-head">@Model.MovieComment</a>
                            <p> <i class="icon-time"></i> 1 hours ago</p>
                        </div>
                    </article>
                    <article class="media">
                        <a class="pull-left thumb p-thumb">
                            <img src="img/avatar-mini2.jpg">
                        </a>
                        <div class="media-body">
                            <a href="#" class="cmt-head">Nulla vel metus scelerisque ante sollicitudin commodo</a>
                            <p> <i class="icon-time"></i> 23 mins ago</p>
                        </div>
                    </article>
                    <article class="media">
                        <a class="pull-left thumb p-thumb">
                            <img src="img/avatar-mini3.jpg">
                        </a>
                        <div class="media-body">
                            <a href="#" class="cmt-head">Donec lacinia congue felis in faucibus. </a>
                            <p> <i class="icon-time"></i> 15 mins ago</p>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </section>

</div>

SinemaSONDeneme/CinemaAutomation-master/CinemaAutomation/Project.MVCUI/Areas/Admin/Views/RealMovie/MovieList.cshtml
@model List<Movie>
@{
    ViewBag.Title = "MovieList";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<link href="~/OuterTools/LightBox/lightbox.min.css" rel="stylesheet" />


<section class="panel">
    <header class="panel-heading">
       <h3 style="color:red"><td class="center hidden-phone">@Html.ActionLink("Film Ekle", "AddMovie", new { @class = "btn btn-warning" })</td></h3> 
    </header>
    <div class="panel-body">
        <div class="adv-table">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
                <thead>
                    <tr>
                        <th>Film IDsi</th>
                        <th>Film İsmi</th>
                        <th>Film Süresi</th>
                        <th>Film Afişi</th>
                        <th>Formatlar</th>
                        <th>Film Açıklaması</th>
                        <th>Vizyon Tarihi</th>
                        <th class="hidden-phone">Türü</th>
                        <th class="hidden-phone">Silme</th>
                        <th class="hidden-phone">Güncelleme</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (Movie item in Model)
                    {
                    <tr class="gradeX">
                        <td>@item.ID</td>
                        <td>@item.MovieName</td>
                        <td>
                            @item.ScreenTime
                        </td>

                        <td>
                            <a href="@item.ImagePath" class="example-image-link" data-lightbox="example-1">

                                <img src="@item.ImagePath" width="100" height="30" />


                            </a>
                        </td>
                        <td>@item.Format</td>
                        <td>@item.MovieSummary</td>
                        <td>@item.ShowDate</td>
                        @if (item.MovieGenre == null)
                        {
                            <td class="hidden-phone">Kategorisi Yok</td>
                        }
                        else
                        {
                            <td class="hidden-phone">@item.MovieGenre.GenreName</td>
                        }


                        <td class="center hidden-phone">@Html.ActionLink("Sil", "DeleteMovie", new { id = item.ID }, new { @class = "btn btn-danger" })</td>
                        <td class="center hidden-phone">@Html.ActionLink("Güncelle", "UpdateMovie", new { id = item.ID }, new { @class = "btn btn-warning" })</td>
                        
                    </tr>
                    }



                </tbody>
            </table>
        </div>
    </div>
</section>
<script src="~/OuterTools/LightBox/lightbox-plus-jquery.min.js"></script>

<script type="text/javascript">
    /* Formating function for row details */
    function fnFormatDetails(oTable, nTr) {
        var aData = oTable.fnGetData(nTr);
        var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
        sOut += '<tr><td>Film İsmi:</td><td>' + aData[2] + ' | Türü: ' + aData[5] + '</td></tr>';
        sOut += '<tr><td>Film Ekleme Sayfası:</td><td> <a href="/Admin/RealMovie/AddMovie">Film Ekle</a></td></tr>';
        sOut += '<tr><td>Detaylar:</td><td> <a href="/Admin/RealMovie/MovieDetail/' + aData[1] + '">Film Detayı</a></td></tr>';
        sOut += '</table>';

        return sOut;
    }

    $(document).ready(function () {
        /*
         * Insert a 'details' column to the table
         */
        var nCloneTh = document.createElement('th');
        var nCloneTd = document.createElement('td');
        nCloneTd.innerHTML = '<img class="brb" src="/OuterTools/movie_review/assets/advanced-datatable/examples/examples_support/details_open.png">';
        nCloneTd.className = "center";

        $('#hidden-table-info thead tr').each(function () {
            this.insertBefore(nCloneTh, this.childNodes[0]);
        });

        $('#hidden-table-info tbody tr').each(function () {
            this.insertBefore(nCloneTd.cloneNode(true), this.childNodes[0]);
        });

        /*
         * Initialse DataTables, with no sorting on the 'details' column
         */
        var oTable = $('#hidden-table-info').dataTable({
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [0] }
            ],
            "aaSorting": [[1, 'asc']]
        });

        /* Add event listener for opening and closing details
         * Note that the indicator for showing which row is open is not controlled by DataTables,
         * rather it is done here
         */
        $('#hidden-table-info tbody td .brb').live('click', function () {
            var nTr = $(this).parents('tr')[0];
            if (oTable.fnIsOpen(nTr)) {
                /* This row is already open - close it */
                this.src = "/OuterTools/movie_review/assets/advanced-datatable/examples/examples_support/details_open.png";
                oTable.fnClose(nTr);
            }
            else {
                /* Open this row */
                this.src = "/OuterTools/movie_review/assets/advanced-datatable/examples/examples_support/details_close.png";
                oTable.fnOpen(nTr, fnFormatDetails(oTable, nTr), 'details');
            }
        });
    });</script>

SinemaSONDeneme/CinemaAutomation-master/CinemaAutomation/Project.MVCUI/Areas/Admin/Views/RealMovie/UpdateMovie.cshtml
@model Tuple<List<MovieGenre>, Movie>
@{
    ViewBag.Title = "UpdateMovie";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="panel-body">
    <div class="form">

        @using (Html.BeginForm("UpdateMovie", "RealMovie", FormMethod.Post, new { @class = "cmxform form-horizontal tasi-form", enctype = "multipart/form-data" }))
        {

            @Html.HiddenFor(x => x.Item2.ID)
            <div class="form-group ">
                <label for="firstname" class="control-label col-lg-2">Film Adı</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.MovieName, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group ">
                <label for="lastname" class="control-label col-lg-2">Film Süresi</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.ScreenTime, new { @class = "form-control", type = "number" })

                </div>
            </div>
            <div class="form-group ">
                <label for="username" class="control-label col-lg-2">Türü</label>
                <div class="col-lg-6">
                    @Html.DropDownListFor(x => x.Item2.MovieGenreID, new SelectList(Model.Item1, "ID", "GenreName"), "Lütfen Seçiniz", new { @class = "form-control" })

                </div>
            </div>
            <div class="form-group ">
                <label for="description" class="control-label col-lg-2">Özet</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.MovieSummary, new { style = "height:100px;width:600px" })
                </div>
            </div>
            <div class="form-group ">
                <label for="password" class="control-label col-lg-2">Formatlar</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.Format, new { @class = "form-control", type = "string" })

                </div>
            </div>
            <div class="form-group ">
                <label for="lastname" class="control-label col-lg-2">Vizyon Tarihi</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.ShowDate, new { @class = "form-control", type = "datetime" })
                </div>
            </div>
            <div class="form-group ">
                <label for="firstname" class="control-label col-lg-2">Yönetmen</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.Director, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group ">
                <label for="firstname" class="control-label col-lg-2">Oyuncular</label>
                <div class="col-lg-6">
                    @Html.TextBoxFor(x => x.Item2.Actors, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-6">
                    <button class="btn btn-danger" type="submit">Save</button>
                    @Html.ActionLink("İptal Et", "MovieList", null, new { @class = "btn btn-default" })

                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-2">Afiş Yükle</label>
                <div class="col-md-9">
                    <div class="fileupload fileupload-new" data-provides="fileupload">
                        <div class="fileupload-new thumbnail" style="width: 570px; height: 516px;">
                            <img src="@Model.Item2.ImagePath" alt="" />
                        </div>
                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                        @if (Model.Item2.ImagePath != "Dosya boş")
                        {
                            @Html.CheckBox("resimSil")
                            <b style="color:red">Resmi Sil?</b>
                        }

                        <div>
                            <span class="btn btn-white btn-file">
                                <span class="fileupload-new"><i class="icon-paper-clip"></i> Fotoğraf Seç</span>
                                <span class="fileupload-exists"><i class="icon-undo"></i> Değiştir</span>
                                <input name="resim" type="file" class="default" />
                            </span>
                            <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="icon-trash"></i> Fotoğrafı Kaldır</a>

                        </div>
                    </div>

                </div>
            </div>
        }
    </div>
</div>